name: 'VDET for Java'
description: 'Analyses Java files for vulnerabilities'

inputs:
  path:
      description: 'Paths to analyse (separated by spaces)'
      required: false
      default: ''
  files:
    description: 'Files to analyse (paths relative to the repository root, separated by spaces)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'docker://up201806461/vdet:latest'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.files }}