  name: Test checkout workflow
  on: push
  jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
        - name: LS Output
          run: ls -a
        - name: Checkout code
          uses: actions/checkout@v3
        - name: LS Output after checkout
          run: ls -a